In [2]:
import numpy as np
import pandas as pd
import datetime as dt

### Read in Restaurant data pickle

In [33]:
restaurants = pd.read_pickle('./restaurants_df.pkl')

In [34]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3231 entries, 15 to 249954
Data columns (total 10 columns):
DBA Name               3231 non-null object
Street Address         3231 non-null object
Source Zipcode         3231 non-null float64
Business Start Date    3231 non-null datetime64[ns]
Business End Date      782 non-null datetime64[ns]
Years Open             3231 non-null float64
Year Opened            3231 non-null int64
Month Opened           3231 non-null int64
Year Closed            782 non-null float64
Success                3231 non-null int64
dtypes: datetime64[ns](2), float64(3), int64(3), object(2)
memory usage: 277.7+ KB

### Neighborhoods (labels match to zipcodes)

In [35]:
# Read in 'Neighborhoods' pickle
neighborhoods = pd.read_pickle('./zipcode_neighborhood_table.pkl')

In [36]:
neighborhoods

    Zip Code                             Neighborhood
0      94102  Hayes Valley/Tenderloin/North of Market
1      94103                          South of Market
2      94107                             Potrero Hill
3      94108                                Chinatown
4      94109             Polk/Russian Hill (Nob Hill)
5      94110             Inner Mission/Bernal Heights
6      94112       Ingelside-Excelsior/Crocker-Amazon
7      94114                        Castro/Noe Valley
8      94115               Western Addition/Japantown
9      94116                     Parkside/Forest Hill
10     94117                           Haight-Ashbury
11     94118                           Inner Richmond
12     94121                           Outer Richmond
13     94122                                   Sunset
14     94123                                   Marina
15     94124                    Bayview-Hunters Point
16     94127    St. Francis Wood/Miraloma/West Portal
17     94131                     Twin Peaks-Glen Park
18     94132                              Lake Merced
19     94133                    North Beach/Chinatown
20     94134              Visitacion Valley/Sunnydale

In [37]:
#Merge with restaurants table --> Lost some data points, maybe can work on that in a later iteration
restaurants = pd.merge(restaurants, neighborhoods, left_on=['Source Zipcode'], right_on=['Zip Code'])

In [38]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2856 entries, 0 to 2855
Data columns (total 12 columns):
DBA Name               2856 non-null object
Street Address         2856 non-null object
Source Zipcode         2856 non-null float64
Business Start Date    2856 non-null datetime64[ns]
Business End Date      704 non-null datetime64[ns]
Years Open             2856 non-null float64
Year Opened            2856 non-null int64
Month Opened           2856 non-null int64
Year Closed            704 non-null float64
Success                2856 non-null int64
Zip Code               2856 non-null int64
Neighborhood           2856 non-null object
dtypes: datetime64[ns](2), float64(3), int64(4), object(3)
memory usage: 290.1+ KB

# Food Type --> Google scrape

In [39]:
restaurants.head()

,DBA Name,Street Address,Source Zipcode,Business Start Date,Business End Date,Years Open,Year Opened,Month Opened,Year Closed,Success,Zip Code,Neighborhood
0,Neem,2948 Folsom St,94110.0,2016-03-29,2017-05-15,1.128767,2016,3,2017.0,0,94110,Inner Mission/Bernal Heights
1,Our Poke Place,3515 20th St Unit B,94110.0,2017-04-20,2019-09-01,2.367123,2017,4,2019.0,0,94110,Inner Mission/Bernal Heights
2,Ox Cafe,798 Van Ness Ave,94110.0,2014-04-10,NaT,5.671233,2014,4,NaN,1,94110,Inner Mission/Bernal Heights
3,Volcano Kimchi,2948 Folsom St,94110.0,2014-05-20,NaT,5.561644,2014,5,NaN,1,94110,Inner Mission/Bernal Heights
4,Rasoi,2948 Folsom St,94110.0,2014-05-15,2018-03-31,3.879452,2014,5,2018.0,0,94110,Inner Mission/Bernal Heights

In [40]:
google_info = pd.read_pickle('./restaurant_scrape.pkl')

In [41]:
google_info

,Business Account Number,DBA Name,Street Address,Source Zipcode,Currently Open,Years Open,Year Opened,Month Opened,Year Closed,Success,Zip Code,Neighborhood,ZHVI_AllHomes,Year,Month,google_results,Rating,Price,Food
3340,1002775,Novy,4000 24 Th St,94114,1.0,4.265753,2015,2,None,1,94114.0,Castro/Noe Valley,1463000.0,2015.0,2.0,"(4.2, $$, Greek restaurant)",4.2,2,Greek restaurant
3535,1007372,Liholiho Yacht Club,871 Sutter St,94109,1.0,4.347945,2015,1,None,1,94109.0,Polk/Russian Hill (Nob Hill),985900.0,2015.0,1.0,"(4.6, $$$, Californian restaurant)",4.6,3,Californian restaurant
3537,1007392,Hillside Supper Club,300 Precita Ave,94110,1.0,4.347945,2015,1,None,1,94110.0,Inner Mission/Bernal Heights,1140000.0,2015.0,1.0,"(4.4, $$, New American restaurant)",4.4,2,New American restaurant
3540,1007473,The Pin Up,772 Folsom St,94108,1.0,4.350685,2015,1,None,1,94108.0,Chinatown,852600.0,2015.0,1.0,"(4.0, Diner, 0)",4.0,5,0
3541,1007479,Belle Cora,565 Green St,94133,1.0,4.336986,2015,1,None,1,94133.0,North Beach/Chinatown,1189000.0,2015.0,1.0,"(4.6, $$, Bar)",4.6,2,Bar
3542,1007507,Red Tavern Inc,2229 Clement St,94121,1.0,4.336986,2015,1,None,1,94121.0,Outer Richmond,1144700.0,2015.0,1.0,"(4.5, $$, Russian restaurant)",4.5,2,Russian restaurant
3544,1007532,Spaghetti Bros.,3213 Scott St,94123,1.0,4.334247,2015,1,None,1,94123.0,Marina,1999000.0,2015.0,1.0,"(4.5, $$, New American restaurant)",4.5,2,New American restaurant
3545,1007532,Spaghetti Brothers,3213 Scott St,94123,1.0,4.334247,2015,1,None,1,94123.0,Marina,1999000.0,2015.0,1.0,"(4.5, $$, New American restaurant)",4.5,2,New American restaurant
3546,1007538,Myriad,2491 Mission St,94110,1.0,4.334247,2015,1,None,1,94110.0,Inner Mission/Bernal Heights,1140000.0,2015.0,1.0,"(4.4, $$, Gastropub)",4.4,2,Gastropub
3549,1007558,Vietnam House,642 Eddy St,94109,1.0,4.331507,2015,1,None,1,94109.0,Polk/Russian Hill (Nob Hill),985900.0,2015.0,1.0,"(4.2, $, Vietnamese restaurant)",4.2,1,Vietnamese restaurant
3552,1007567,Cafe Cole,609 Cole St,94117,1.0,4.350685,2015,1,None,1,94117.0,Haight-Ashbury,1295100.0,2015.0,1.0,"(4.2, $, Coffee shop)",4.2,1,Coffee shop
3553,1007572,Jo Jo's Cafe,1537 Ocean Ave,94112,1.0,4.350685,2015,1,None,1,94112.0,Ingelside-Excelsior/Crocker-Amazon,753200.0,2015.0,1.0,"(4.3, $, Dinner theater)",4.3,1,Dinner theater
3554,1007573,Cookie Love,1488 Pine St,94109,1.0,4.331507,2015,1,None,1,94109.0,Polk/Russian Hill (Nob Hill),985900.0,2015.0,1.0,"(4.4, $, Cookie shop)",4.4,1,Cookie shop
3555,1007575,Sally's Restaurant And Deli,300 De Haro St #332,94103,1.0,4.331507,2015,1,None,1,94103.0,South of Market,885100.0,2015.0,1.0,"(4.0, $, American restaurant)",4.0,1,American restaurant
3556,1007581,The Flame Llc,1801 Clement St,94121,1.0,4.331507,2015,1,None,1,94121.0,Outer Richmond,1144700.0,2015.0,1.0,"(4.1, $$, 0)",4.1,2,0
3559,1007641,Rusty's Southern Llc,750 Ellis St,94109,1.0,4.320548,2015,1,None,1,94109.0,Polk/Russian Hill (Nob Hill),985900.0,2015.0,1.0,"(4.5, $$, Southern restaurant (US))",4.5,2,Southern restaurant (US)
3564,1007723,Tj Cups Inc,2437 Noriega St,94122,1.0,4.339726,2015,1,None,1,94122.0,Sunset,986600.0,2015.0,1.0,"(4.5, $, Bubble tea store)",4.5,1,Bubble tea store
3565,1007737,Octavia,1701 Octavia St,94109,1.0,4.315068,2015,1,None,1,94109.0,Polk/Russian Hill (Nob Hill),985900.0,2015.0,1.0,"(4.6, $$$$, New American restaurant)",4.6,4,New American restaurant
3566,1004192,Origami Market,669 Townsend St,94103,1.0,4.315068,2015,1,None,1,94103.0,South of Market,885100.0,2015.0,1.0,"(4.4, $$, Japanese restaurant)",5.0,1,0
3567,1007779,Go Jojo's Mojo,55 Duboce Ave,94103,1.0,4.334247,2015,1,None,1,94103.0,South of Market,885100.0,2015.0,1.0,"(3.8, Takeout Restaurant, 0)",3.8,18,0
3570,1007830,California Bakery,77 Mcallister St,94102,1.0,4.350685,2015,1,None,1,94102.0,Hayes Valley/Tenderloin/North of Market,767000.0,2015.0,1.0,"(4.2, $, 0)",4.2,1,0
3573,1007919,Growing Up Farms,5801 Mission St,94112,1.0,4.315068,2015,1,None,1,94112.0,Ingelside-Excelsior/Crocker-Amazon,753200.0,2015.0,1.0,"(0, Farm in San Francisco, California, 0)",0,33,0
3574,1007936,The Pots,2652 Judah St,94122,1.0,4.326027,2015,1,None,1,94122.0,Sunset,986600.0,2015.0,1.0,"(4.5, $$, Hot pot restaurant)",4.5,2,Hot pot restaurant
3577,1007966,Tycoon Cafe & Restaurant,620 Ofarrell St,94109,1.0,4.295890,2015,1,None,1,94109.0,Polk/Russian Hill (Nob Hill),985900.0,2015.0,1.0,"(4.3, $$, Thai restaurant)",4.3,2,Thai restaurant
3578,1007980,Hawker Fare,680 Valencia St,94110,1.0,4.293151,2015,1,None,1,94110.0,Inner Mission/Bernal Heights,1140000.0,2015.0,1.0,"(4.2, $$, Laotian restaurant)",4.2,2,Laotian restaurant
3582,1008082,Laksa,1005 Guerrero St,94110,1.0,4.312329,2015,1,None,1,94110.0,Inner Mission/Bernal Heights,1140000.0,2015.0,1.0,"(4.2, $, Vietnamese restaurant)",4.2,1,Vietnamese restaurant
3583,1008100,Celtic Coffee Company,142 Mcallister St,94102,1.0,4.282192,2015,1,None,1,94102.0,Hayes Valley/Tenderloin/North of Market,767000.0,2015.0,1.0,"(4.3, $$, Cafe)",4.3,2,Cafe
3584,1008138,Little Sweet,3836 Geary Blvd,94118,1.0,4.282192,2015,1,None,1,94118.0,Inner Richmond,1639200.0,2015.0,1.0,"(4.4, $, Bubble tea store)",4.4,1,Bubble tea store
3585,1008176,Little Beijing Restaurant,1316 Noriega St,94122,1.0,4.279452,2015,1,None,1,94122.0,Sunset,986600.0,2015.0,1.0,"(4.1, Chinese restaurant, 0)",4.1,18,0
3589,1008211,Fuji Restaurant,301 West Portal Ave,94127,1.0,4.279452,2015,1,None,1,94127.0,St. Francis Wood/Miraloma/West Portal,1289500.0,2015.0,1.0,"(4.3, $$, Japanese restaurant)",4.3,2,Japanese restaurant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8610,1030942,The Salzburg,663 Union St,94133,0.0,1.794521,2016,5,2018,0,94133.0,North Beach/Chinatown,1313500.0,2016.0,5.0,"(4.5, $$, Wine bar)",4.6,2,0
8611,1077260,Rangoon Ruby Burmese Cuisine,590 Van Ness Ave,94102,0.0,0.580822,2017,10,2018,0,94102.0,Hayes Valley/Tenderloin/North of Market,884400.0,2017.0,10.0,"(4.0, $$, Burmese restaurant)",4.0,2,Burmese restaurant
8616,1077490,J & D's Bbq Llc,110 Hunters Point Shipyard,94124,0.0,0.063014,2017,10,2017,0,94124.0,Bayview-Hunters Point,857300.0,2017.0,10.0,"(0, 0, 0)",,0,0
8622,1077669,Pearl,6101 California St,94121,0.0,0.726027,2017,10,2018,0,94121.0,Outer Richmond,1435300.0,2017.0,10.0,"(4.6, Restaurant, 0)",4.6,10,0
8624,1077801,Coffee Bar,1890 Bryant Street St Ste 100,94110,0.0,1.315068,2017,9,2019,0,94110.0,Inner Mission/Bernal Heights,1388100.0,2017.0,9.0,"(4.3, $$, 0)",4.3,2,0
8625,1077918,Base Camp Bakery,2066 Chestnut St,94123,0.0,0.191781,2017,10,2018,0,94123.0,Marina,2255900.0,2017.0,10.0,"(4.0, $$, French restaurant)",4.0,2,French restaurant
8626,1077938,Martitas Kitchen,2560 Marin St,94124,0.0,1.021918,2017,10,2018,0,94124.0,Bayview-Hunters Point,857300.0,2017.0,10.0,"(4.2, $, Mexican restaurant)",4.2,1,Mexican restaurant
8629,1078484,U Dessert Story,280 Guttenbert St,94112,0.0,0.063014,2017,10,2017,0,94112.0,Ingelside-Excelsior/Crocker-Amazon,974700.0,2017.0,10.0,"(4.5, Dessert restaurant, 0)",4.5,18,0
8630,1037039,La Rica Benny Llc,2948 Folsom St,94110,0.0,0.536986,2017,11,2018,0,94110.0,Inner Mission/Bernal Heights,1438900.0,2017.0,11.0,"(0, 0, 0)",5.0,52,0
8631,1037039,La Rica Benny,2948 Folsom St,94110,0.0,1.936986,2016,6,2018,0,94110.0,Inner Mission/Bernal Heights,1227600.0,2016.0,6.0,"(0, 0, 0)",5.0,52,0
8641,1078947,Naan N Curry,4238 18th St,94114,0.0,1.024658,2017,10,2018,0,94114.0,Castro/Noe Valley,1712300.0,2017.0,10.0,"(3.9, Indian restaurant, 0)",3.9,17,0
8645,1019415,Uberwaffle,Bldg 110 Hunter's Point Shipyard,94124,0.0,2.128767,2015,10,2017,1,94124.0,Bayview-Hunters Point,748600.0,2015.0,10.0,"(4.2, Artist in San Francisco, California, 0)",4.2,35,0
8647,1079168,Coffee Bar,433 Kearny St,94108,0.0,1.038356,2017,9,2018,0,94108.0,Chinatown,1040500.0,2017.0,9.0,"(0, Coffee shop, 0)",0,11,0
8650,1079211,Doordash,139 Ankeny St St,94134,0.0,1.523288,2016,11,2018,0,94134.0,Visitacion Valley/Sunnydale,810400.0,2016.0,11.0,"(1.7, Corporate office, 0)",1.7,16,0
8655,1079413,The Pine Tar Grill And Bar,917 Folsom St,94107,0.0,0.052055,2017,11,2017,0,94107.0,Potrero Hill,1195300.0,2017.0,11.0,"(4.6, Sports bar, 0)",4.6,10,0
8658,1079710,Postmates,475 Valencia St,94103,0.0,0.328767,2016,2,2016,0,94103.0,South of Market,992400.0,2016.0,2.0,"(2.3, Association or organization, 0)",2.3,27,0
8660,199359,Go Go 7,1300 Oceanview Ave,94112,0.0,0.041096,2017,11,2017,0,94112.0,Ingelside-Excelsior/Crocker-Amazon,986800.0,2017.0,11.0,"(4.7, Restaurant, 0)",4.7,10,0
8661,199359,Go Go 7,1300 Ocean Ave,94112,0.0,0.041096,2017,11,2017,0,94112.0,Ingelside-Excelsior/Crocker-Amazon,986800.0,2017.0,11.0,"(4.7, Restaurant, 0)",4.7,10,0
8664,1079901,Chullo,474 3rd St,94107,0.0,0.482192,2017,11,2018,0,94107.0,Potrero Hill,1195300.0,2017.0,11.0,"(4.2, Indian restaurant, 0)",4.2,17,0
8668,1080381,Raavi Indian Nepalese,1063 Market St,94103,0.0,0.336986,2017,12,2018,0,94103.0,South of Market,1007500.0,2017.0,12.0,"(4.4, $, Indian restaurant)",4.4,1,Indian restaurant
8669,1080506,Papi's Sf,846 Geary,94109,0.0,0.057534,2017,12,2018,0,94109.0,Polk/Russian Hill (Nob Hill),1193700.0,2017.0,12.0,"(4.5, $$, Mexican restaurant)",4.5,2,Mexican restaurant
8672,1080785,Curry Underground,356 Kearny St,94108,0.0,0.235616,2017,12,2018,0,94108.0,Chinatown,1154800.0,2017.0,12.0,"(4.1, $$, Ramen restaurant)",4.1,2,Ramen restaurant
8677,1080785,Udon Underground,356 Kearny St,94108,0.0,0.200000,2017,12,2018,0,94108.0,Chinatown,1154800.0,2017.0,12.0,"(4.1, $$, Ramen restaurant)",4.1,2,Ramen restaurant
8678,1081136,China Delights,295 Orizaba B,94132,0.0,0.298630,2017,12,2018,0,94132.0,Lake Merced,1152000.0,2017.0,12.0,"(3.6, Chinese restaurant, 0)",3.6,18,0
8679,1068433,Oren's Hummus Sf1 Llc,71 Third St,94103,0.0,0.123288,2017,12,2018,0,94103.0,South of Market,1007500.0,2017.0,12.0,"(4.5, $$, Mediterranean restaurant)",4.5,2,Mediterranean restaurant
8733,1080968,Kokio Republic,428 11th St,94109,0.0,1.060274,2017,12,2018,0,94109.0,Polk/Russian Hill (Nob Hill),1193700.0,2017.0,12.0,"(4.3, $$, Food Court)",4.3,2,Food Court
8759,1085512,Grinders Pizzeria,2741 Judah St Apt 2,94122,0.0,0.246575,2017,12,2018,0,94122.0,Sunset,1380300.0,2017.0,12.0,"(4.2, $, Pizza restaurant)",4.2,1,Pizza restaurant
8773,1034157,409 Bryant St,409 Bryant St,94107,0.0,1.087671,2017,7,2018,0,94107.0,Potrero Hill,1167100.0,2017.0,7.0,"(4.0, 0, 0)",4.0,0,0
8785,1016642,Bootleg Bar & Kitchen,2360 Van Ness Ave,94109,0.0,3.257534,2015,7,2018,1,94109.0,Polk/Russian Hill (Nob Hill),1095000.0,2015.0,7.0,"(4.4, Bar, 0)",4.4,3,0
8898,1097031,Lavash,511 Irving Street,94122,0.0,3.830137,2015,3,2019,1,94122.0,Sunset,1032700.0,2015.0,3.0,"(4.2, $$, 0)",4.2,2,0

In [42]:
restaurants = pd.merge(restaurants, google_info, on=['DBA Name'])

In [43]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1774 entries, 0 to 1773
Data columns (total 30 columns):
DBA Name                   1774 non-null object
Street Address_x           1774 non-null object
Source Zipcode_x           1774 non-null float64
Business Start Date        1774 non-null datetime64[ns]
Business End Date          398 non-null datetime64[ns]
Years Open_x               1774 non-null float64
Year Opened_x              1774 non-null int64
Month Opened_x             1774 non-null int64
Year Closed_x              398 non-null float64
Success_x                  1774 non-null int64
Zip Code_x                 1774 non-null int64
Neighborhood_x             1774 non-null object
Business Account Number    1774 non-null int64
Street Address_y           1774 non-null object
Source Zipcode_y           1774 non-null int64
Currently Open             1774 non-null float64
Years Open_y               1774 non-null float64
Year Opened_y              1774 non-null int64
Month Opened_y             1774 non-null int64
Year Closed_y              630 non-null object
Success_y                  1774 non-null int64
Zip Code_y                 1774 non-null float64
Neighborhood_y             1774 non-null object
ZHVI_AllHomes              1774 non-null float64
Year                       1774 non-null float64
Month                      1774 non-null float64
google_results             1774 non-null object
Rating                     1774 non-null object
Price                      1774 non-null int64
Food                       1774 non-null object
dtypes: datetime64[ns](2), float64(9), int64(10), object(9)
memory usage: 429.6+ KB

In [21]:
# Definitely duplicates now

In [44]:
# Drop redundant columns
restaurants.drop(columns=['Business Account Number', 'Street Address_y', 
                          'Source Zipcode_y', 'Currently Open', 
                          'Years Open_y', 'Year Opened_y', 
                          'Month Opened_y', 'Year Closed_y', 
                          'Success_y', 'Zip Code_y', 
                          'Neighborhood_y', 'ZHVI_AllHomes', 
                          'Year', 'Month'], inplace=True)

In [45]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1774 entries, 0 to 1773
Data columns (total 16 columns):
DBA Name               1774 non-null object
Street Address_x       1774 non-null object
Source Zipcode_x       1774 non-null float64
Business Start Date    1774 non-null datetime64[ns]
Business End Date      398 non-null datetime64[ns]
Years Open_x           1774 non-null float64
Year Opened_x          1774 non-null int64
Month Opened_x         1774 non-null int64
Year Closed_x          398 non-null float64
Success_x              1774 non-null int64
Zip Code_x             1774 non-null int64
Neighborhood_x         1774 non-null object
google_results         1774 non-null object
Rating                 1774 non-null object
Price                  1774 non-null int64
Food                   1774 non-null object
dtypes: datetime64[ns](2), float64(3), int64(5), object(6)
memory usage: 235.6+ KB

## Walk score of location